### ISSUE TITLE
Login without verifying the email address

### ISSUE THREAD

**Issue by msvamp** [dev-kasibhatla/krissues#3]
**Note:** This trick (bug?) works only once immediately after registering because it is not possible to login with the actual login form.

## Steps to reproduce
1. Open the app clean (not already logged in)
2. Tap the _SIGN UP_ button and fill out all the details
3. Tap the _Register_ button and wait for the registration process to complete
4. You will be redirected to the Login form automatically
5. Press the back navigation button and close the app
6. Open the app again
7. Hooray! You've logged in without confirming the email address

```
App version: 1.0.0 (Debug)
Android version: 10 (LineageOS 17.1)
```

**Comment by msvamp** [comment]
Also tested the above behaviour with `App version 1.0 (Release)` the build @dev-kasibhatla personally sent to me at 13-08-2020 19:48.
At Step 6, app freezes at black screen instead of working normally.

However this line appears in the logcat, which probably means login succeeded -

```
08-13 20:18:05.900  3852  3894 I flutter : {Orders: {totalSpent: 0, totalOrders: 0}, pincode: , address: , wallet: 0, gender: , city: , pVer: false, eVer: false, walletHistory: , phone: , name: , age: 0, email: notaditya@notkasibhatla.com}
```

**Comment by dev-kasibhatla** [comment]
:smile: thank you for that amazing bug report
fixing on priority

**Comment by dev-kasibhatla** [comment]
I tested a fix and it works
Please check the new apk and if it works fine, close this issue

**Comment by msvamp** [comment]
Upgraded the app from `1.0 (Release)` to `1.0.2 (Release)` (the build @dev-kasibhatla personally sent to me on 13-08-2020 at 22:36).

The app doesn't freeze on black screen anymore, and doesn't log me in either, it takes me to the `welcome screen`. But it appears like the app is performing only a *cosmetic* logout, because I still see the following lines in the logcat even after opening the app multiple times -
```
08-14 13:26:56.349   862   882 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.inator.Krushinavakalpana/.MainActivity bnds=[30,1008][234,1313]} from uid 10236
08-14 13:26:56.711  4767  5125 I flutter : returning container
08-14 13:26:56.746   399   399 E Layer   : [Surface(name=AppWindowToken{dfaace0 token=Token{aef7ae3 ActivityRecord{acc8312 u0 com.inator.Krushinavakalpana/.MainActivity t79}}})/@0xffb3b36 - animation-leash#0] No local sync point found
08-14 13:26:56.770  4767  5125 I flutter : Pressed 8 times.
08-14 13:26:56.781  4767  5125 I flutter : Fetching app data
08-14 13:26:56.795  4767  5125 I flutter : returning container
08-14 13:26:56.818   862   898 I ActivityTaskManager: Displayed com.inator.Krushinavakalpana/.MainActivity: +443ms
08-14 13:26:56.820   862   898 I ActivityTaskManager: Fully drawn com.inator.Krushinavakalpana/.MainActivity: +470ms
08-14 13:26:57.553  4767  5125 I flutter : apocalypse: false
08-14 13:26:57.553  4767  5125 I flutter : min version: 1
08-14 13:26:57.950  4767  5125 I flutter : {Orders: {totalSpent: 0, totalOrders: 0}, pincode: , address: , wallet: 0, gender: , city: , pVer: false, eVer: false, walletHistory: , phone: , name: , age: 0, email: notaditya@notkasibhatla.com}
08-14 13:26:57.979  4767  5125 I flutter : Opening welcome screen
```
This explains that the user state is maintained even though the app pretends that the user isn't logged in.

---

Also tested the above behaviour after cleaning the app data and repeating [the steps](https://github.com/dev-kasibhatla/krissues/issues/3#issue-678491975) again. I can still see that the auth state has persisted although the app pretends like it isn't logged in.

After steps 1-4 -
```
08-14 13:56:41.178  7702  7720 D FirebaseAuth: Notifying id token listeners about user ( pqOjMe948tPflIuVhfBB5UeSEdD3 ).
08-14 13:56:41.183  7702  7720 D FirebaseAuth: Notifying auth state listeners about user ( pqOjMe948tPflIuVhfBB5UeSEdD3 ).
08-14 13:56:41.211  7702  7731 I flutter : stored in firedb
08-14 13:56:41.237  7702  7731 I flutter : User status updated
08-14 13:56:41.245  7702  7731 I flutter : After registration, user status: 1
```

After step 6 -
```
08-14 14:01:03.542   862  8209 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.inator.Krushinavakalpana/.MainActivity bnds=[30,612][234,917]} from uid 10236
08-14 14:01:03.960   399   399 E Layer   : [Surface(name=AppWindowToken{2d6bbe1 token=Token{d405148 ActivityRecord{e7ccfeb u0 com.inator.Krushinavakalpana/.MainActivity t82}}})/@0xa5da0bf - animation-leash#0] No local sync point found
08-14 14:01:04.079  7702  8801 I flutter : returning container
08-14 14:01:04.097  7702  8801 I flutter : Pressed 2 times.
08-14 14:01:04.099  7702  8801 I flutter : returning container
08-14 14:01:04.101  7702  8801 I flutter : Fetching app data
08-14 14:01:04.126  7702  8801 I flutter : returning container
08-14 14:01:04.139   862   898 I ActivityTaskManager: Displayed com.inator.Krushinavakalpana/.MainActivity: +557ms
08-14 14:01:04.168   862   898 I ActivityTaskManager: Fully drawn com.inator.Krushinavakalpana/.MainActivity: +625ms
08-14 14:01:06.296  7702  8801 I flutter : apocalypse: false
08-14 14:01:06.296  7702  8801 I flutter : min version: 1
08-14 14:01:09.048  7702  8801 I flutter : {Orders: {totalSpent: 0, totalOrders: 0}, pincode: , address: , wallet: 0, gender: , city: , pVer: false, eVer: false, walletHistory: , phone: , name: , age: 0, email: 9wkowjeoskeneoe@89wiwjw0w0.com}
08-14 14:01:09.078  7702  8801 I flutter : Opening welcome screen
```

If the auth state is deliberately stored, why should you take the user to the welcome screen?
You can instead display a message like "*Your email address has not been verified, please verify it from the link in the received mail."* with an optional logout button in case he/she entered a wrong email address during registration.

Also, does this mean that if I close the app after registration and confirm my email address and come back to the app, I will get signed in automatically without having to login with my credentials again? Is this behaviour really expected?

**Comment by dev-kasibhatla** [comment]
Auth state is not deliberately stored. Google manages it and i query it.
I'll make it a point to perform a logout unsuccessful login attempt to clear token data.

**Comment by dev-kasibhatla** [comment]
```Also, does this mean that if I close the app after registration and confirm my email address and come back to the app, I will get signed in automatically without having to login with my credentials again? Is this behaviour really expected?```

I don't think you would. Please try and report

**Comment by dev-kasibhatla** [comment]
I'm quite sure this issue is fixed.
If yes, please close it @msvamp

**Comment by msvamp** [comment]
> I don't think you would. Please try and report

Could not see this happen in `Version 1.0.2` (both `release-14-08-20_13-51-23` and `release-15-08-20-14_13_30`) so I guess that issue doesn't really exist.

> I'll make it a point to perform a logout unsuccessful login attempt to clear token data.

Still cannot see this implemented in the latest `release-15-08-20-14_13_30`. I can still see the Firebase Auth object requesting user data in the logcat although the app pretends to have signed out. Is it very difficult to call [one function](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/signOut.html) after signup succeeds?

Anyway, since the original issue is resolved, I am closing this issue.

**Comment by dev-kasibhatla** [comment]
Yes I still haven't done that. But it doesn't cause any problem, and i don't see why we need to clear auth data from cache.

**Comment by msvamp** [comment]
No problem in leaving it, but I don't like apps that lie to me by taking to the login screen although a session already exists.
Also, it might account for the wrong actions in Firebase Analytics (i.e. actions that user performed without being apparently logged in, will be recorded as performed post-login in Analytics).

Btw, we are using Firebase Analytics, right?

**Comment by dev-kasibhatla** [comment]
We are going to, but not yet. Forgot to add it in 1.0.3
Anywho, I'll add it in the next release.

**Comment by dev-kasibhatla** [comment]
We are going to, but not yet. Forgot to add it in 1.0.3
Anywho, I'll add it in the next release.

**Comment by dev-kasibhatla** [comment]
By add it, i mean both: firebase analytics and login data clearing.
